// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20230523071536_init3")]
    partial class init3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("T_ArticleS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b8d20d21-44b1-43e4-8c19-8871415761aa"),
                            Author = "jack",
                            CreateTime = new DateTime(2023, 5, 23, 15, 15, 36, 553, DateTimeKind.Local).AddTicks(8779),
                            CreateUser = "admin",
                            Description = "crm",
                            Title = "迅达crm",
                            UpdateTime = new DateTime(2023, 5, 23, 15, 15, 36, 553, DateTimeKind.Local).AddTicks(8788),
                            UpdateUser = "admin"
                        },
                        new
                        {
                            Id = new Guid("b312e5b1-e914-4c95-8be2-7c2d5de2c214"),
                            Author = "jimmiy",
                            CreateTime = new DateTime(2023, 5, 23, 15, 15, 36, 553, DateTimeKind.Local).AddTicks(8816),
                            CreateUser = "admin",
                            Description = "efrqc",
                            Title = "efrqc",
                            UpdateTime = new DateTime(2023, 5, 23, 15, 15, 36, 553, DateTimeKind.Local).AddTicks(8816),
                            UpdateUser = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
