// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20230523071956_init4")]
    partial class init4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("T_ArticleS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cc468cd6-02b2-4c49-8cbb-2f5525c32086"),
                            Author = "jack",
                            CreateTime = new DateTime(2023, 5, 23, 15, 19, 56, 894, DateTimeKind.Local).AddTicks(6825),
                            CreateUser = "admin",
                            Description = "crm",
                            Title = "迅达crm",
                            UpdateTime = new DateTime(2023, 5, 23, 15, 19, 56, 894, DateTimeKind.Local).AddTicks(6836),
                            UpdateUser = "admin"
                        },
                        new
                        {
                            Id = new Guid("8c6f2876-c646-48cb-892f-2646c5ecf08d"),
                            Author = "jimmiy",
                            CreateTime = new DateTime(2023, 5, 23, 15, 19, 56, 894, DateTimeKind.Local).AddTicks(6861),
                            CreateUser = "admin",
                            Description = "efrqc",
                            Title = "efrqc",
                            UpdateTime = new DateTime(2023, 5, 23, 15, 19, 56, 894, DateTimeKind.Local).AddTicks(6862),
                            UpdateUser = "admin"
                        },
                        new
                        {
                            Id = new Guid("73e4b822-1ee6-4dc1-8bdf-177b69c107b3"),
                            Author = "rock",
                            CreateTime = new DateTime(2023, 5, 23, 15, 19, 56, 894, DateTimeKind.Local).AddTicks(6864),
                            CreateUser = "admin",
                            Description = "tuoxin",
                            Title = "tuoxin",
                            UpdateTime = new DateTime(2023, 5, 23, 15, 19, 56, 894, DateTimeKind.Local).AddTicks(6864),
                            UpdateUser = "admin"
                        },
                        new
                        {
                            Id = new Guid("9c33c5b7-7091-40e2-bfd5-01b0517b21f7"),
                            Author = "john",
                            CreateTime = new DateTime(2023, 5, 23, 15, 19, 56, 894, DateTimeKind.Local).AddTicks(6881),
                            CreateUser = "admin",
                            Description = "good",
                            Title = "good",
                            UpdateTime = new DateTime(2023, 5, 23, 15, 19, 56, 894, DateTimeKind.Local).AddTicks(6882),
                            UpdateUser = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
